all: crust filling meringue
	./combine.sh crust filling meringue
	./cook.sh 375 45

filling:
	./combine.sh lemon butter sugar

meringue:
	./combine.sh eggwhites sugar

crust:
	./combine.sh flour butter water
